Development
armornetworkdev/armor-explorer pull request #4
Opened 2021-02-10 17:35 UTC by username1565

Add ability to search block by height or depth, too.

2021-02-11 12:01 UTC, moshenskyDV requested changes

2021-02-11 12:01 UTC, moshenskyDV commented on views/search_block.pug
> +            input#hash.form-control(type='text' name='hash' placeholder='Insert block or transaction hash, or positive block-number (height) or negative depth-number.' value=`${hash}`)
Also I think we should display block number above of hash if it's possible.

2021-02-11 17:48 UTC, username1565 commented on views/search_block.pug
> +            input#hash.form-control(type='text' name='hash' placeholder='Insert block or transaction hash, or positive block-number (height) or negative depth-number.' value=`${hash}`)
Done. There needed to write `#{result.block.header.hash}`, not `#{result.block.hash}`.
Also, added `#{result.block.header.height}` to dispay block-number.

2021-02-11 23:49 UTC, moshenskyDV commented
Please squash your commits into single commit. You can do this by next command
`git rebase -i HEAD~10`
(where 10 - count of your last commits in PR)

Lets do not make trash can from the repository. Best behavior - one feature = one commit (that's why I created separate PR for meta tags - one feature = one commit).

2021-02-12 06:46 UTC, username1565 commented
> Please squash your commits into single commit. You can do this by next command
> `git rebase -i HEAD~10`
> (where 10 - count of your last commits in PR)

Is this really necessary to rebase all commits?
After all, you can see full changes here: 
[https://github.com/armornetworkdev/armor-explorer/pull/4/files](![image](https://user-images.githubusercontent.com/39200328/107737822-3f551b80-6cfd-11eb-81df-87961248c196.png))
to do not see the changes by each commit, if so many commits there.
 
> Lets do not make trash can from the repository. Best behavior - one feature = one commit (that's why I created separate PR for meta tags - one feature = one commit).

I'm not using `git`,
I using github web-interfase,
so sometimes I can make `1 commit` for change `1 line`. 
![image](https://user-images.githubusercontent.com/39200328/107737727-04eb7e80-6cfd-11eb-85bc-2e08e49125eb.png)

I tryed to write the command `git rebase -i HEAD~3`, for last 3 commits, and there is opened `vim`.

2021-02-12 07:22 UTC, username1565 commented
> `git rebase -i HEAD~10`

Попытался сделать `git rebase -i HEAD~10`
И не пашет оно, один файл изменён, а не 3. 
Ещё и деанон можно схватить по имени компа и пользователю. Придётся менять всё теперь.
![image](https://user-images.githubusercontent.com/39200328/107740259-99a4ab00-6d02-11eb-86c1-0e56db25df2b.png)
Смотрите полный дифф сами, короче. Там всё элементарно.
Несмотря на то, что куча коммитов, один коммит на строку - всего-то, там пару строк изменено,
и не нужно пугаться числа коммитов этих вот.
Посмотрели всё сразу, и слили PR. У меня всё.

2021-02-12 08:17 UTC, username1565 commented
1. Пытался объединить три последних коммита в ветке `development`:
` git rebase -i HEAD~3`
прописал в `vim` `p` (`pick`).
` git commit --amend`
`git rebase --continue`
`git push origin development --force`
логин, пароль. 

Получился один коммит https://github.com/armornetworkdev/armor-explorer/commit/9fb81ea7fdac2c06ccc840ffc99b0bdb62f20c23 с одним файлом, и никакого ребейса 3-х коммитов.

2. Затем, откатился назад:
`git reset --hard 78f81bd519ffa848b475b65fc72c6fb1f6fabd40`
`git push --force` + логин, пароль.

Вижу что осталось два коммита, а не 3.

3. Повторил `1.`, но вместо `p` (`pick`), указал `s`(`squash`) в `vim`. Результат - коммит https://github.com/Armor-Network/armor-explorer/commit/c5a652047fe9c948076e2f8cd1d862f37c86ca18
тоже с одним файлом, а не с тремя.

В итоге, получилось ещё больше коммитов, вместо объединения 3-х последних.
Чем они вам так глаза мозолят эти коммиты?
Пусть их хоть миллиард будет, в полном diff всё-равно может быть изменена одна лишь строка.

2021-02-12 08:19 UTC, username1565 commented
@moshenskyDV Данила, это всё тебе.

2021-02-12 08:37 UTC, username1565 commented
И ещё `npm install pug@3.0.0` присуньте, куда-нибудь в `package.json`,
потому что `npm install` и `npm update`, оно это как уязвимость расценивает,
котрую нужно решать вручную, через `npm audit`, `npm audit fix`, `npm audit fix --forse`, и так далее, и тому подобное.
Пусть оно и без возни, и автоматом ставится, вместе с пакетами, если не установлен `pug`.

2021-02-12 08:39 UTC, moshenskyDV commented
@username1565 you told you do commits through browser github... Have you ever tested your code?

The last decision on @armornetworkdev, I can just advice.

2021-02-12 08:48 UTC, moshenskyDV commented
The purpose of small amount of commits - its clean history and possibility to easy rollback the feature if something went wrong.

2021-02-12 08:56 UTC, username1565 commented
Yes, I tested `the code` before opened the `pull-request`. But when `Pull-Request` is `not accepted`, and new commits added, then this commits adding to the pull-request, just because the `branch`, from which old pull-request was been opened,
this branch was been updated.
Maybe, will be better, to create a `new branch` (`temp-changes`, for example), and create this from the `old branch`,
then add some commits in `new branch`, then test this commits, and merge this with `old-branch`, for which Pull-request was been opened.
In this case one commit of merge will be added in the `Pull-Request`, or many commits, I'm not sure.

2021-02-12 12:28 UTC, armornetworkdev commented
I created a new branch called "dev". Please open all PR against dev branch and please use a single commit for each PR. In this way everything will be better organized.

2021-02-12 12:28 UTC, closed without merging